name = "Ells Pack"
author = "Mofo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d60c216415a94d0e7deeab0b3f13d96ab0fb8bc7feb1b51567a0772885ca2b8e"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
